name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml
    - name: Deploy with Maven
      run: mvn -B deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PWD }}
